version: '3.6'

services:
  app:
    image: jamirperoba/laravel_php74_nginx_fpm:3.1
    container_name: app
    restart: always
    ports:
      - 8091:80
    volumes:
      - ./:/usr/share/nginx
    networks:
      - network-test
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
  minio1:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    container_name: minio1
    volumes:
      - minio_data_1_1:/data1
      - minio_data_1_2:/data2
    networks:
      - network-test
    ports:
    - "9002:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    volumes:
      - minio_data_2_1:/data1
      - minio_data_2_2:/data2
    networks:
      - network-test
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    volumes:
      - minio_data_3_1:/data1
      - minio_data_3_2:/data2
    networks:
      - network-test
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    volumes:
      - minio_data_4_1:/data1
      - minio_data_4_2:/data2
    networks:
      - network-test
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio{1...4}/data{1...2}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
#  minio:
#    image: minio/minio
#    container_name: minio
#    ports:
#      - 9000:9000
#    networks:
#      - network-test
#    environment:
#      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
#      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
#    volumes:
#      - minio_v:/data
#      - logvolume01:/var/log

networks:
  network-test:
    name: network-test
    driver: bridge

volumes:
  minio_data_1_1:
  minio_data_1_2:
  minio_data_2_1:
  minio_data_2_2:
  minio_data_3_1:
  minio_data_3_2:
  minio_data_4_1:
  minio_data_4_2:

