version: '3.6'

services:
  app:
    image: jamirperoba/laravel_php74_nginx_fpm:3.1
    container_name: app
    restart: always
    ports:
      - 8091:80
    volumes:
      - ./:/usr/share/nginx
    networks:
      - network-test
    depends_on:
      - minio
  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    container_name: minio
    volumes:
      - minio_data_1:/data1
      - minio_data_2:/data2
    networks:
      - network-test
    ports:
    - "9003:9000"
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server http://minio/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  network-test:
    name: network-test
    driver: bridge

volumes:
  minio_data_1:
  minio_data_2:

